# Generated by Django 6.0.5 on 2026-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pressure', models.IntegerField()),
                ('temp', models.FloatField()),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low Pressure'), ('CRITICAL', 'Critical'), ('OVERPRESSURE', 'Overpressure'), ('OFFLINE', 'Offline')], default='NORMAL', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('engineer', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
